**Email Address: dipuhaider@gmail.com**

In [ ]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


Answer to the **Q1**

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv("employees.csv")

ages = df["age"].to_numpy()
salaries = df["salary"].to_numpy()

print(ages)
print(salaries)

print(ages.dtype)
print(ages.ndim)
print(ages.shape)
print(ages.size)

print(salaries.dtype)
print(salaries.ndim)
print(salaries.shape)
print(salaries.size)

[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10
int64
1
(10,)
10


**Answer to the Q2**

In [ ]:
highest_sal = np.max(salaries)
lowest_sal = np.min(salaries)
avg_sal = np.mean(salaries)
avg_age = np.mean(ages)

print(highest_sal)
print(lowest_sal)
print(avg_sal)
print(avg_age)

89735
30769
57446.9
38.5


**Answer to the Q3**

In [ ]:
age_over_30 = ages[ages>30]
count_over_30 = age_over_30.size

print(age_over_30)
print(count_over_30)

[56 46 32 38 56 36 40]
7


**Answer to the Q4**

In [ ]:
age_increase_by_5 = ages + 5

print(age_increase_by_5)

[61 51 37 30 43 61 41 45 33 33]


**Answer to the Q5**

In [ ]:
total_salary = np.sum(salaries)
diff_salary = np.max(salaries) - np.min(salaries)

print(total_salary)
print(diff_salary)

574469
58966


**Answer to the Q6**

In [ ]:
print(df.head(5))
print(df.info())
print(df.describe(include="all"))

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
              id       age        salary dept
count   10.00000  10.00000     10.000000   10
unique       NaN       NaN           NaN    4
top          NaN       NaN           NaN   HR
freq         NaN       NaN           NaN    3
mean     5.50000  38.50000  57446.900000  NaN
std      3.02765  11.16791  24357.262884  NaN
min      1.00000  25.00000  30769.000000  NaN
25%      3.25000  29.00000  33152.500000  NaN
50%      5.50000  37.00000  58556.500000 

**Answer to the Q7**

In [ ]:
specific = df[["id", "age", "salary"]]

print(specific.tail(3))

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


**Answer to the Q8**

In [ ]:
it_dept = df.loc[df["dept"] == "IT"]

print(it_dept)
print(it_dept.shape[0])

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


**Answer to the Q9**

In [ ]:
top_3_emp = df.sort_values(by="salary", ascending=False).loc[:, ["id", "salary", "dept", "age"]].head(3)
print(top_3_emp)

   id  salary     dept  age
6   7   89735  Finance   36
7   8   86101       IT   40
0   1   77191       HR   56


**Answer to the Q10**

In [ ]:
salary_value= df.copy()
salary_value.loc[salary_value["salary"] > 80000, "salary"] = 80000

print(salary_value[["id", "salary"]])

new_avg_salary = salary_value["salary"].mean()
print(new_avg_salary)

   id  salary
0   1   77191
1   2   74131
2   3   46023
3   4   71090
4   5   31685
5   6   30769
6   7   80000
7   8   80000
8   9   32433
9  10   35311
55863.3
